# openapi: 3.0.0
# info:
#   title: "Social App"
#   description: "My First Social App at LCO - Yash"
#   version: 1.0.1

# servers:
#   - url: https://social-app-pro-backend.cyclic.app/
#     description: Main (production) server
#   - url: http://localhost:4000/
#     description: Local Host Version of our app

openapi: 3.0.0
info:
  title: Social App
  description: My First Social App at LCO - Yash
  version: 1.0.1

servers:
  - url: https://social-app-pro-backend.cyclic.app/
    description: Main (production) server
  - url: http://localhost:4000/
    description: Local Host Version of the app

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /api/v1/instagram:
    get:
      summary: returns username, followers & follows
      responses:
        "200": # status code
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: number
                  follows:
                    type: number

  /api/v1/facebook:
    get:
      summary: returns username, followers & follows
      responses:
        "200": # status code
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: number
                  follows:
                    type: number

  /api/v1/linkedin:
    get:
      summary: returns username, followers & follows
      responses:
        "200": # status code
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: number
                  follows:
                    type: number

  /api/v1/{url}:
    get:
      summary: returns whatever is there in parameter
      parameters:
        - name: url
          default: 5
          in: path
          schema:
            type: string
      responses:
        "200": # status code
          description: returns an object
          content:
            application/json:
              schema:
                type: object
                properties:
                  reqUrl:
                    type: string
